### PR TITLE
Rewrite autonumbering function to fix #391.

### LINKED ISSUE #391: Autonumbering gives keyerror
When I run autonumbering on a folder with one album, the first track gets processed, but it stops with the second track. Python error:
`Traceback (most recent call last):`
`  File "/usr/lib/python2.7/site-packages/puddlestuff/puddletag.py", line 775, in writeTags
    ret = self._write(tagiter, rows, previews)`
  `File "/usr/lib/python2.7/site-packages/puddlestuff/puddletag.py", line 734, in _write
    [setRowData(row, f, undo=True) for row, f in izip(rows, tagiter)]`
 ` File "/usr/lib/python2.7/site-packages/puddlestuff/mainwin/funcs.py", line 416, in tagiter
    val = function(rowtags.get(field, u''), rowtags, state, r_tags=f)`
  `File "/usr/lib/python2.7/site-packages/puddlestuff/findfunc.py", line 844, in runFunction
    return func(**topass)`
 `File "/usr/lib/python2.7/site-packages/puddlestuff/functions.py", line 98, in autonumbering
    tracknum = state['autonumbering'][index]`
`KeyError: 2
`
Using puddletag 1.2.0-1 in archlinux up to date.

### PR DESCRIPTION
**Pull request by terbshaeusser**
Hi there,

this PR fixes the problem described in #391 where keyerrors are raised, when the autonumbering function is used.

Fixes #391

### CODE REVIEW

**Comment by blueblots** [comment]
Hi terbshaeusser, if you include in your PR message, "Fixes #391", then it links the pull request to the issue so it will automatically close when the PR is merged. Also it will bring your PR to the attention of the maintainer(s), and make it easier for them to assess.

Just a random tip because I noticed this one has been sitting here for some time.

**Comment by terbshaeusser** [comment]
Hi @blueblots,

thanks for your comment. I can already see a link to this PR in the issue. So I guess the commit message was already correct.
The issue seems quite old and that not many people have this problem (don't know why, because I use the autonumbering feature quite often ...).
However, please correct me if I'm wrong with the issue link ;)

**Comment by blueblots** [comment]
Hi @terbshaeusser ,

The link you see in the issue is a *reference* rather than a link (in the linked issue sense); this just lets people following the issue know that the its been mentioned in a pull request. If the PR were to be merged now, that issue would remain open even though its been resolved.

The difference between the reference and a "link" is that when an issue is linked to a PR its supposed to automatically close when the PR gets merged, and if you look at the sidebar on the website it will list the issue as being "linked" (you can see an example of this at #604 if you look at the github website).

As far as I'm aware, the only way to get Github to properly link an issue to a pull request is to put a line like `Fixes: #000` in the commit message, on its own line (doesn't seem to work otherwise).

Its not a big deal, its just a convenience to close issues that have already been solved. I don't know if it has any other purpose :).

I hope you find it useful later anyway.

**Comment by terbshaeusser** [comment]
Hi @blueblots,

once again thanks for your comment. The commit message should now contain the necessary string. Always nice to learn something new ;)

**Comment by sandrotosi** [comment]
@terbshaeusser i'm afraid that was not enough: you may want to read https://docs.github.com/en/github/managing-your-work-on-github/managing-your-work-with-issues-and-pull-requests/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword on the details on how to close an issue using a PR.

that usually just means add a "Fixes Xnnn" in the _pull request description_, when opening it

**Review by sandrotosi — APPROVED** [review]

**Comment by sandrotosi** [comment]
that being said, the PR looks good so i merged it -- thanks for your contribution @terbshaeusser !

**Pull request merged**
