### PR TITLE
Update pyparsing usage to PEP-8

### LINKED ISSUE #695: Use PyParsing snake_case names
In October 2021, PyParsing released its version 3.0.0. One of the many changes is the switch of the naming scheme from camelCase to snake_case, in an effort to adopt the naming convention laid out by the widely used [PEP-8 Style Guide for Python Code](https://www.python.org/dev/peps/pep-0008/). The [news document](https://github.com/pyparsing/pyparsing/blob/master/docs/whats_new_in_3_0_0.rst) also contains in chapter 2 "API Changes" a (I assume mostly-exhaustive) list of the changed names. To make migration easy, it still includes aliases/synonyms for all the camelCase names to their snake_case counterparts for the time being, but they also note that "The compatibility synonyms will be removed in a future version".

Because of the compatibility synonyms, there is no immediate need for action/change. In fact, as of today many major linux distributions do not package/ship PyParsing v3 yet, so it would be a mistake to migrate puddletag right now. The only way to run it would be by installing the dependencies via pip directly. We already had some issues with deprecated features in v3 (see e.g. #643), but those were very minor in nature.

This issue mainly exists as a reference, and to keep track that this will have to be done at some point.

### PR DESCRIPTION
**Pull request by corubba**
## Use PyParsing snake_case names
PyParsing has adopted PEP-8. Replaced all the compatibility synonyms with the new snake_case names.

Fixes #695 

## Improve packrat enablement
It's a static method, so follow the [upstream recommendation](https://github.com/pyparsing/pyparsing/blob/3.1.2/pyparsing/core.py#L1107) to a) call it on the class and b) shortly after the import.

### CODE REVIEW

**Comment by audiomuze** [comment]
@sandrotosi, can we get this PR merged, please.

**Comment by sandrotosi** [comment]
thanks @corubba !

**Comment by willp** [comment]
I got puddletag to work by adding to puddlestuff/audio_filter.py on line 6, just after "from pyparsing import *" this one line:
```
ParserElement.enable_packrat()
```

**Comment by VictorSago** [comment]
> I got puddletag to work by adding to puddlestuff/audio_filter.py on line 6, just after "from pyparsing import *" this one line:
> 
> ```
> ParserElement.enable_packrat()
> ```

I can confirm that this solution works on Debian Testing, with Puddletag v2.3.0 and python3-pyparsing v3.1.2-1.

After some packages were updated in the last few days, puddletag stopped working. Doing the changes described here, it works as before.

**Comment by pled** [comment]
same here, thanks.

**Pull request merged**
