### PR TITLE
Fix tagsources get_encoding

### PR DESCRIPTION
**Pull request by bernd-wechner**
This method leans on the html.parser module and that by specification only accepts strings:

https://docs.python.org/3/library/html.parser.html#html.parser.HTMLParser.feed

It cannot therefore be sensibly used to divine the encoding of a byte-string and this whole block of code is  redundant. Likely a carry over from the Python 2 to 3 conversion.

Moreover I can find no reference in nay documentation to a FoundEncoding exception and no idea where that is implemented but certainly not by html.parser.

### CODE REVIEW

**Comment by sandrotosi** [comment]
i'm afraid you still have spurious commits

**Comment by bernd-wechner** [comment]
I noticed. Git is a nightmare ;-). Working on it.

**Comment by sandrotosi** [comment]
if it makes it easier, i'm on with you including this change in #669 as 2 separate commits

**Comment by bernd-wechner** [comment]
I've finally got it. Basically it's a case of making sure my fork master is identical to the upstream master, branching cleanly and cherrypicking the single commit onto it and PR that. But there were some tangles with recent upstream master commits etc.  Establishing a smooth workflow slowly.

**Pull request closed without merging**
